require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe KotaController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Kotum. As you add validations to Kotum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KotaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all kota as @kota" do
      kotum = Kotum.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:kota)).to eq([kotum])
    end
  end

  describe "GET #show" do
    it "assigns the requested kotum as @kotum" do
      kotum = Kotum.create! valid_attributes
      get :show, {:id => kotum.to_param}, valid_session
      expect(assigns(:kotum)).to eq(kotum)
    end
  end

  describe "GET #new" do
    it "assigns a new kotum as @kotum" do
      get :new, {}, valid_session
      expect(assigns(:kotum)).to be_a_new(Kotum)
    end
  end

  describe "GET #edit" do
    it "assigns the requested kotum as @kotum" do
      kotum = Kotum.create! valid_attributes
      get :edit, {:id => kotum.to_param}, valid_session
      expect(assigns(:kotum)).to eq(kotum)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Kotum" do
        expect {
          post :create, {:kotum => valid_attributes}, valid_session
        }.to change(Kotum, :count).by(1)
      end

      it "assigns a newly created kotum as @kotum" do
        post :create, {:kotum => valid_attributes}, valid_session
        expect(assigns(:kotum)).to be_a(Kotum)
        expect(assigns(:kotum)).to be_persisted
      end

      it "redirects to the created kotum" do
        post :create, {:kotum => valid_attributes}, valid_session
        expect(response).to redirect_to(Kotum.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved kotum as @kotum" do
        post :create, {:kotum => invalid_attributes}, valid_session
        expect(assigns(:kotum)).to be_a_new(Kotum)
      end

      it "re-renders the 'new' template" do
        post :create, {:kotum => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested kotum" do
        kotum = Kotum.create! valid_attributes
        put :update, {:id => kotum.to_param, :kotum => new_attributes}, valid_session
        kotum.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested kotum as @kotum" do
        kotum = Kotum.create! valid_attributes
        put :update, {:id => kotum.to_param, :kotum => valid_attributes}, valid_session
        expect(assigns(:kotum)).to eq(kotum)
      end

      it "redirects to the kotum" do
        kotum = Kotum.create! valid_attributes
        put :update, {:id => kotum.to_param, :kotum => valid_attributes}, valid_session
        expect(response).to redirect_to(kotum)
      end
    end

    context "with invalid params" do
      it "assigns the kotum as @kotum" do
        kotum = Kotum.create! valid_attributes
        put :update, {:id => kotum.to_param, :kotum => invalid_attributes}, valid_session
        expect(assigns(:kotum)).to eq(kotum)
      end

      it "re-renders the 'edit' template" do
        kotum = Kotum.create! valid_attributes
        put :update, {:id => kotum.to_param, :kotum => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested kotum" do
      kotum = Kotum.create! valid_attributes
      expect {
        delete :destroy, {:id => kotum.to_param}, valid_session
      }.to change(Kotum, :count).by(-1)
    end

    it "redirects to the kota list" do
      kotum = Kotum.create! valid_attributes
      delete :destroy, {:id => kotum.to_param}, valid_session
      expect(response).to redirect_to(kota_url)
    end
  end

end
